import { QuestionTypeCode } from '@utils/enums';

export const ListWorQuestionCodes: QuestionTypeCode[] = [
  QuestionTypeCode.W3,
  QuestionTypeCode.W6,
  QuestionTypeCode.W11,
  QuestionTypeCode.W7,
  QuestionTypeCode.W2,
  QuestionTypeCode.W4,
  QuestionTypeCode.W12,
  QuestionTypeCode.W9,
  QuestionTypeCode.W8,
  QuestionTypeCode.W13,
  QuestionTypeCode.W14,
];

export const ListSentenceQuestionCodes: QuestionTypeCode[] = [
  QuestionTypeCode.S12,
  QuestionTypeCode.S10,
  QuestionTypeCode.S1,
  QuestionTypeCode.S2,
  QuestionTypeCode.S14,
  QuestionTypeCode.S17,
  QuestionTypeCode.S7,
  QuestionTypeCode.S15,
  QuestionTypeCode.S16,
  QuestionTypeCode.S4,
  QuestionTypeCode.S18,
];
export const MultipleChoiceCode: QuestionTypeCode[] = [
  QuestionTypeCode.W3,
  QuestionTypeCode.W6,
  QuestionTypeCode.W2,
  QuestionTypeCode.W4,
  QuestionTypeCode.W13,
  QuestionTypeCode.S10,
  QuestionTypeCode.S7,
];
export const booksName = [
  'Tiếng Anh 1 Macmillan',
  'Tiếng Anh 2 Macmillan',
  'Tiếng Anh 3 Tập 1',
  'Tiếng Anh 3 Tập 2',
  'Tiếng Anh 4 Tập 1',
  'Tiếng Anh 4 Tập 2',
  'Tiếng Anh 5 Tập 1',
  'Tiếng Anh 5 Tập 2',
  'Tiếng Anh 6 Tập 1',
  'Tiếng Anh 6 Tập 2',
  'Tiếng Anh 7 Tập 1',
  'Tiếng Anh 7 Tập 2',
  'Tiếng Anh 8 Tập 1',
  'Tiếng Anh 8 Tập 2',
  'Tiếng Anh 9 Tập 1',
  'Tiếng Anh 9 Tập 2',
  'Tiếng Anh 10 Tập 1',
  'Tiếng Anh 10 Tập 2',
  'Tiếng Anh 11 Tập 1',
  'Tiếng Anh 11 Tập 2',
  'Tiếng Anh 12 Tập 1',
  'Tiếng Anh 12 Tập 2',
  'Tiếng Anh 1 2020',
  'Tiếng Anh 2 (CT GDPT 2018)',
];
export const TOP_XP_LENGTH = 10;
