export const WORD_CLASSIFY_MAPPING = new Map<string, string>();
WORD_CLASSIFY_MAPPING.set('N', 'noun');
WORD_CLASSIFY_MAPPING.set('ADJ', 'adjective');
WORD_CLASSIFY_MAPPING.set('ADV', 'adverb');
WORD_CLASSIFY_MAPPING.set('V', 'verb');
WORD_CLASSIFY_MAPPING.set('C', 'connective');
WORD_CLASSIFY_MAPPING.set('PN', 'pronoun');
WORD_CLASSIFY_MAPPING.set('PP', 'preposition');
WORD_CLASSIFY_MAPPING.set('DT', 'determiner');
WORD_CLASSIFY_MAPPING.set('MV', 'modal verb');
